app/models.py
# -*- coding: UTF-8 -*- 
__author__ = 'agmcs'
from app import db, loginManager
from flask.ext.login import UserMixin, AnonymousUserMixin
from werkzeug.security import check_password_hash, generate_password_hash
from datetime import datetime

#用户
class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(128),unique=True)
    name = db.Column(db.String(64),unique=True)
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise "Password cant be read"

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password_hash,password)

    def __repr__(self):
        return "<User %r>" %self.name

    def __unicode__(self):
        return self.name


#文章
class Article(db.Model):
    __tablename__ = 'articles'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(25), nullable=False)
    body = db.Column(db.Text, nullable=False)
    modify_date = db.Column(db.DateTime, default=datetime.utcnow)
    category_id = db.Column(db.Integer, db.ForeignKey('categorys.id'))
    def __repr__(self):
        return "<Article %r>" %self.title

    def __unicode__(self):
        return self.title


tag_article = db.Table('registrations',
                       db.Column('tag_id',db.Integer,db.ForeignKey('tags.id')),
                       db.Column('article_id',db.Integer,db.ForeignKey('articles.id'))
                       )


class Tag(db.Model):
    __tablename__ = 'tags'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(24))
    articles = db.relationship('Article',
                               secondary = tag_article,
                               backref=db.backref('tags',lazy = 'dynamic'),
                               lazy='dynamic')

    def __repr__(self):
        return "<Tag %r>" %self.name

    def __unicode__(self):
        return self.name


#友情链接
class FriendLink(db.Model):
    __tablename__ = 'friendlinks'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))
    url = db.Column(db.String(120))

    def __repr__(self):
        return "<FriendLink %r>" %self.name

    def __unicode__(self):
        return self.name


class Category(db.Model):
    __tablename__ = 'categorys'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30))
    articles = db.relationship('Article',backref = 'category', lazy = 'dynamic')

    def __repr__(self):
        return "<Category %r>" %self.name

    def __unicode__(self):
        return self.name



@loginManager.user_loader
def load(user_id):
    return User.query.get(int(user_id))

app/__init__.py
# -*- coding: UTF-8 -*-
from flask.ext.admin.menu import MenuLink

__author__ = 'agmcs'
from flask import Flask, url_for
from flask.ext.login import LoginManager
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.moment import Moment
from flask.ext.admin import Admin
from flask.ext.bootstrap import Bootstrap
from Config import config
loginManager = LoginManager()
loginManager.session_protection = 'strong'
loginManager.login_view = 'auth.login'
bootstrap = Bootstrap()


db = SQLAlchemy()
moment = Moment()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    loginManager.init_app(app)
    db.init_app(app)
    moment.init_app(app)
    bootstrap.init_app(app)


    #Blueprint
    from main import main
    app.register_blueprint(main)
    #admin

    from app.admins.adminViews import MyIndexView,PostView,UserView,FriendLinkView,TagView,CategoryView
    from app.models import User,Article,FriendLink,Tag, Category
    admin = Admin(app = app,template_mode='bootstrap3',name='Hei', endpoint='admin',index_view=MyIndexView())
    admin.add_view(PostView(Article,db.session,name=u'文章管理'))
    admin.add_view(FriendLinkView(FriendLink,db.session,name=u'友情链接'))
    admin.add_view(TagView(Tag,db.session,name=u'标签管理'))
    admin.add_view(CategoryView(Category,db.session,name=u'分类管理'))

    return app

app/admins/__init__.py
# -*- coding: UTF-8 -*- 
__author__ = 'agmcs'

app/main/__init__.py
# -*- coding: UTF-8 -*- 
__author__ = 'agmcs'
from flask import Blueprint

main = Blueprint('main', __name__)

from .import views

app/main/views.py
# -*- coding: UTF-8 -*- 
__author__ = 'agmcs'
from . import main
from flask import render_template, abort, request
from app.models import Article, Tag, FriendLink, Category


@main.route('/search',methods=['GET','POST'])
def search():

    text = request.args.get('search','')
    page = request.args.get('p', 1, type=int)
    pagenation = Article.query.filter(Article.title.like('%' + text + '%')).order_by(Article.modify_date.desc()).paginate(page, per_page=7, error_out = False)
    posts = pagenation.items

    return render_template('index.html', pagenation = pagenation, posts = posts, **global_map())


def global_map():
    tags = Tag.query.all()
    links = FriendLink.query.all()
    categorys = Category.query.all()
    map = {
         'tags': tags,
         'links': links,
         'categorys':categorys
    }
    return map


@main.route('/')
def index():
    page = request.args.get('p', 1, type=int)
    pagenation = Article.query.order_by(Article.modify_date.desc()).paginate(page, per_page=7, error_out = False)
    posts = pagenation.items
    return render_template('index.html', pagenation = pagenation, posts = posts, **global_map())


@main.route('/p/<int:id>')
def article(id):
    post = Article.query.get_or_404(int(id))
    return render_template('article.html',post = post, **global_map())

@main.route('/tag/<int:id>')
def by_tag(id):
    tag = Tag.query.get_or_404(id)

    page = request.args.get('p', 1, type=int)
    pagenation = tag.articles.paginate(page, per_page=7, error_out = False)
    posts = pagenation.items
    return render_template('by_tag.html', pagenation = pagenation,id=id, posts = posts, **global_map())


@main.route('/category/<int:id>')
def by_category(id):
    category = Category.query.get_or_404(int(id))

    page = request.args.get('p', 1, type=int)
    pagenation = category.articles.paginate(page, per_page=7, error_out = False)
    posts = pagenation.items
    return render_template('by_category.html', pagenation = pagenation,id=id, posts = posts, **global_map())

app/templates/article.html
{% extends 'base.html' %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript" src="http://v3.jiathis.com/code_mini/jia.js" charset="utf-8"></script>
{% endblock %}

{% block rightbody %}

            <h1 style="margin-top: 25px;margin-bottom:0px;color: #555"><strong>{{ post.title }}</strong></h1>
            <h4 style="margin-top: 0px;margin-bottom:2px;color: #555"><small>1,234 views</small></h4>
            <h4 style="margin: 0px;"><small>{{ moment(post.modify_date).format('MMMM D, YYYY') }}</small></h4>

            <div style="padding-top: 30px;padding-bottom: 30px;padding-right: 50px">
                {{ post.body |safe }}
            </div>

            <div class="jiathis_style" style="padding-top: 20px">
                <span style="float: left;line-height: 18px!important;font-size: 14px">分享到:&nbsp;</span>
                <a class="jiathis_button_qzone"></a>
                <a class="jiathis_button_tsina"></a>
                <a class="jiathis_button_tqq"></a>
                <a class="jiathis_button_weixin"></a>
                <a class="jiathis_button_renren"></a>
                <a class="jiathis_button_xiaoyou"></a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                <a class="jiathis_counter_style"></a>
            </div>

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    <div class="navbar-default navbar-static-top" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="navbar-header">
                <a href="{{ url_for('main.index') }}" class="navbar-logo">
                    <img src="{{ url_for('static',filename='img/avatar.png') }}" style="width: 45px">
                </a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}" class="active">首页</a></li>
                <li><a href="#">留言</a> </li>
                <li><a href="#">关于我</a> </li>
            </ul>

            <form class="navbar-form navbar-right" action="{{ url_for('main.search') }}" method="get">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search..." name="search">
                        <span class="input-group-btn">
                            <input class="btn btn-default" type="submit">Go</input>
                        </span>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container" style="margin-top: 8px">
        <div class="row">
            <!--侧边栏-->
            <div class="col-md-3">
                <!--个人信息-->
                <div class="thumbnail">
                    <img src="{{ url_for('static',filename='img/avatar.png') }}">

                    <!--<div class="thumbnail">-->
                        <!--<img src="avatar.png">-->
                    <!--</div>-->
                    <div class="caption">
                        <div style="text-align: center" class="lead">The pretty girls are AOA.</div>
                    </div>
                </div>

                <!--标签-->
                <div class="thumbnail">
                    <div class="caption">
                        <strong>标签</strong>
                    </div>

                    <div class="container-fluid">
                        {% for tag in tags %}
                            <a href="{{ url_for('main.by_tag', id = tag.id) }}" class="badge">{{ tag.name }}</a>
                        {% endfor %}
                    </div>
                </div>

                <!--分类目录-->
                <div class="list-group">
                    <div class="list-group-item"><strong>分类目录</strong></div>
                    {% for category in categorys %}
                    <a href="{{ url_for('main.by_category',id = category.id) }}" class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>


                <div class="thumbnail">
                    <div class="caption">
                        <strong>热评文章</strong>
                    </div>
                    <div class="container">
                        <ul class="list-unstyled">
                            <li><a href="#">Android开源库</a></li>
                            <li><a href="#">关于我 </a></li>
                            <li><a href="#">回望</a></li>
                            <li><a href="#">Python开元库</a></li>
                            <li><a href="#">手头</a></li>
                            <li><a href="#">小熊词典</a></li>
                            <li><a href="#">我这几年的变化</a></li>
                        </ul>
                    </div>
                </div>

                <!--友情连接-->
                <div class="thumbnail">
                    <div class="caption">
                        <strong>友情连接</strong>
                    </div>
                    <ul >
                        {% for link in links %}
                            <li><a href="{{ link.url }}">{{ link.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <!--<div class="list-group">-->
                    <!--<div class="list-group-item"><strong>友情连接</strong></div>-->
                    <!--<a href="#" class="list-group-item">左岸读书</a>-->
                    <!--<a href="#" class="list-group-item">叶科忠的博客</a>-->
                    <!--<a href="#" class="list-group-item">不给力的面条</a>-->
                    <!--<a href="#" class="list-group-item">代码家</a>-->
                    <!--<a href="#" class="list-group-item">博客大全</a>-->
                    <!--<a href="#" class="list-group-item">NoGameNoLife</a>-->
                    <!--<a href="#" class="list-group-item">Trinea@Android @Java @性能优化</a>-->
                <!--</div>-->



                    </div>

                <!--文章-->
                <div class="col-md-9">
                {% block rightbody %}
                        {% block postlist %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p class="lead"><strong>为什么四轴飞行器没有载人应用</strong></p>
                        我最近买了一架四轴飞行器的遥控飞机来玩，玩了两天之后，我必须承认，在我玩过的所有飞机中，四轴飞行器无论是操作性还是稳定性都非常优秀，在无人机领域里面最顶尖的大疆，也是做这样形状的四轴飞行器的。但是我发现，四轴飞行器的飞行结构，似乎只出现在无人机里面，而并没有载人的四轴飞行器。
                    </div>
                    <div class="panel-footer">
                        n 2015-04-18 - 2 Comment
                    </div>
                </div>
                {% endblock %}

                {% block paginatebar %}
                <!--分页条-->
                <ul class="pagination">
                {% if pagenation.has_prev %}
                    <li><a href="{{ url_for('main.index',_method='GET', p = pagenation.page-1) }}">Prev</a> </li>
                    {% endif %}


                {% for page in pagenation.iter_pages() %}
                    {% if page %}
                        {% if page != pagenation.page %}
                        <li><a href="{{ url_for('main.index',_method='GET', p = page) }}">{{ page }}</a> </li>
                            {% else %}
                        <li><a href="{{ url_for('main.index',_method='GET', p = page) }}">#</a> </li>
                            {% endif %}
                    {% endif %}
                {% endfor %}


                {% if pagenation.has_next %}
                    <li><a href="{{ url_for('main.index',_method='GET', p = pagenation.page + 1) }}">Next</a> </li>
                {% endif %}
                </ul>
                {% endblock %}
            {% endblock %}
            </div>

        </div>
    </div>


{% endblock %}


{% block scripts %}
{{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang('zh-CN') }}
{% endblock %}

app/templates/bolg.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="css/bootstrap.css" rel="stylesheet"/>

</head>


<div class="navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">
                <img src="a11.png" style="width: 45px">
            </a>
        </div>
        <ul class="nav navbar-nav">
            <li><a href="#" class="active">首页</a></li>
            <li><a href="#">文章</a> </li>
            <li><a href="#">分类</a> </li>
            <li><a href="#">评论</a> </li>
            <li><a href="#">留言</a> </li>
            <li><a href="#">关于我</a> </li>
        </ul>

        <!--<ul class="nav navbar-nav navbar-right">-->
            <!--<li>-->
                <!--<a class="btn dropdown-toggle" data-toggle="dropdown">Skkg<span class="caret"></span> </a>-->
                <!--<ul class="dropdown-menu">-->
                    <!--<li><a href="#">个人中心</a> </li>-->
                    <!--<li><a href="#">退出</a> </li>-->
                <!--</ul>-->
            <!--</li>-->
        <!--</ul>-->
        <form class="navbar-form navbar-right">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default">Go</button>
                    </span>
            </div>
        </form>
    </div>
</div>


<body>

<div class="container" style="margin-top: 8px">
    <div class="row">
        <!--侧边栏-->
        <div class="col-md-3">
            <!--个人信息-->
            <div class="thumbnail">
                <img src="a11.png">

                <!--<div class="thumbnail">-->
                    <!--<img src="avatar.png">-->
                <!--</div>-->
                <div class="caption">
                    <div style="text-align: center" class="lead">The pretty girls are AOA.</div>
                </div>
            </div>

            <!--标签-->
            <div class="thumbnail">
                <div class="caption">
                    <strong>标签</strong>
                </div>

                <div class="container-fluid">
                    <a href="#" class="badge">Python</a>
                    <a href="#" class="badge">Android</a>
                    <a href="#" class="badge">机器学习</a>
                    <a href="#" class="badge">C++</a>
                    <a href="#" class="badge">心情</a>
                    <a href="#" class="badge">flask</a>
                    <a href="#" class="badge">算法</a>
                    <a href="#" class="badge">Java</a>
                    <a href="#" class="badge">Web</a>
                    <a href="#" class="badge">日常</a>
                    <a href="#" class="badge">DUDU</a>
                </div>
            </div>

            <!--分类目录-->
            <div class="list-group">
                <div class="list-group-item"><strong>分类目录</strong></div>
                <a href="#" class="list-group-item">互联网</a>
                <a href="#" class="list-group-item">文字</a>
                <a href="#" class="list-group-item">随笔</a>
                <a href="#" class="list-group-item">音乐</a>
            </div>


            <div class="thumbnail">
                <div class="caption">
                    <strong>热评文章</strong>
                </div>
                <div class="container">
                    <ul class="list-unstyled">
                        <li><a href="#">Android开源库</a></li>
                        <li><a href="#">关于我 </a></li>
                        <li><a href="#">回望</a></li>
                        <li><a href="#">Python开元库</a></li>
                        <li><a href="#">手头</a></li>
                        <li><a href="#">小熊词典</a></li>
                        <li><a href="#">我这几年的变化</a></li>
                    </ul>
                </div>
            </div>

            <!--友情连接-->
            <div class="thumbnail">
                <div class="caption">
                    <strong>友情连接</strong>
                </div>
                <ul >
                    <li><a href="#">左岸读书</a></li>
                    <li><a href="#">代码家</a></li>
                    <li><a href="#">NoGameNoLife</a></li>
                    <li><a href="#">Trinea@Android @Java @性能优化</a></li>
                </ul>
            </div>
            <!--<div class="list-group">-->
                <!--<div class="list-group-item"><strong>友情连接</strong></div>-->
                <!--<a href="#" class="list-group-item">左岸读书</a>-->
                <!--<a href="#" class="list-group-item">叶科忠的博客</a>-->
                <!--<a href="#" class="list-group-item">不给力的面条</a>-->
                <!--<a href="#" class="list-group-item">代码家</a>-->
                <!--<a href="#" class="list-group-item">博客大全</a>-->
                <!--<a href="#" class="list-group-item">NoGameNoLife</a>-->
                <!--<a href="#" class="list-group-item">Trinea@Android @Java @性能优化</a>-->
            <!--</div>-->



        </div>


        <!--文章-->
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p class="lead"><strong>为什么四轴飞行器没有载人应用</strong></p>
                    我最近买了一架四轴飞行器的遥控飞机来玩，玩了两天之后，我必须承认，在我玩过的所有飞机中，四轴飞行器无论是操作性还是稳定性都非常优秀，在无人机领域里面最顶尖的大疆，也是做这样形状的四轴飞行器的。但是我发现，四轴飞行器的飞行结构，似乎只出现在无人机里面，而并没有载人的四轴飞行器。
                </div>
                <div class="panel-footer">
                    n 2015-04-18 - 2 Comment
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">
                    <p class="lead"><strong>从理科到文科</strong></p>
                    刚转完专业不久，就有人建议我写一篇文章，聊聊从理科到文科是个什么感受，我那时候告诉他，再等等吧。
                    等着等着，恍然发现，我已经当了快一年的文科生了，虽然广播电视新闻这个专业文的不是很彻底，但终究算是文科，不过和我想象的总之还是是有很多不同。
                    文科和理科最大的区别就在于班上女生的人数，这曾经是相当吸引我的一点，但后来变得几乎不重要，我发现我很想念曾经班上活蹦乱跳的一群哥们，当然，我是直男。
                    也并不是说现在班上的哥们就不活蹦乱跳，他们也是跳的，但是跳的并不是很响亮，我耳朵一听，整个教室还是女生的声音占了主流，叽叽喳喳的一片，有时候连上课也不停，颇为让人烦闷。
                </div>
                <div class="panel-footer">
                    By Admin on 2015-04-18 - 2 Comment
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <p class="lead"><strong>我的一天（视频）</strong></p>
                    借着专业课的作业机会，拍了人生第一个视频作品，这个视频是我用运动相机绑在脑袋上拍的，后期剪辑使用Pr

                    你可以通过这个视频来了解我一天都干些啥，最后有彩蛋
                </div>
                <div class="panel-footer">
                    By Admin on 2015-04-18 - 2 Comment
                </div>
            </div>
            <div class="panel panel-default">

                <div class="panel-body">
                    <p class="lead"><strong>烟雨西湖</strong></p>

                    本来这篇文章的题目应该叫作『艳遇西湖』，但是由于我在上一个贤者时间段内保持着冷静，所以拒绝了那个因为喜欢我文章而表示愿意和我做点成年人游戏的杭州姑娘。于是这次杭州之行就变得单纯而正直。对于期待着一篇小黄文的读者来说，我感到非常抱歉。

                    在去杭州之前，我已经在没有水的城市待了太久。此后我站在河边感觉河水滔滔，此前我站在海边感觉海水滔滔，但站在西湖边，我却只觉得天地之美，造化之妙，都凝聚在这一汪湖水之中了。

                    人工痕迹丝毫不遮挡自然的鬼斧神工，却与之相辅相成，这是我从未感受过的神奇。那一座桥是唐代所建造，这一条堤是苏轼所修，今天的我们可以站在岸边，看着五百年前的湖水拍打着五百年前的

                </div>
                <div class="panel-footer">
                    By Admin on 2015-04-18 - 2 Comment
                </div>
            </div>


            <!--分页条-->
            <ul class="pagination">
                <li><a href="#">Prev</a> </li>
                <li><a href="#">1</a> </li>
                <li><a href="#">2</a> </li>
                <li><a href="#">Next</a> </li>
            </ul>
        </div>

    </div>
</div>



<script src="jquery/jquery-2.1.3.js"></script>
<script src="js/bootstrap.js"></script>
</body>
</html>

app/templates/by_category.html
{% extends 'index.html' %}


{% block paginatebar %}
<!--分页条-->
<ul class="pagination">
{% if pagenation.has_prev %}
    <li><a href="{{ url_for('main.by_category',_method='GET',id=id, p = pagenation.page-1) }}">Prev</a> </li>
    {% endif %}


{% for page in pagenation.iter_pages() %}
    {% if page %}
        {% if page != pagenation.page %}
        <li><a href="{{ url_for('main.by_category',_method='GET', p = page,id=id) }}">{{ page }}</a> </li>
            {% else %}
        <li><a href="{{ url_for('main.by_category',_method='GET', p = page,id=id) }}">#</a> </li>
            {% endif %}
    {% endif %}
{% endfor %}


{% if pagenation.has_next %}
    <li><a href="{{ url_for('main.by_category',_method='GET',id=id, p = pagenation.page + 1) }}">Next</a> </li>
{% endif %}
</ul>
{% endblock %}

app/templates/by_tag.html
{% extends 'index.html' %}

{% block paginatebar %}
<!--分页条-->
<ul class="pagination">
{% if pagenation.has_prev %}
    <li><a href="{{ url_for('main.by_tag',_method='GET',id=id, p = pagenation.page-1) }}">Prev</a> </li>
    {% endif %}


{% for page in pagenation.iter_pages() %}
    {% if page %}
        {% if page != pagenation.page %}
        <li><a href="{{ url_for('main.by_tag',_method='GET',id=id, p = page) }}">{{ page }}</a> </li>
            {% else %}
        <li><a href="{{ url_for('main.by_tag',_method='GET',id=id, p = page) }}">#</a> </li>
            {% endif %}
    {% endif %}
{% endfor %}


{% if pagenation.has_next %}
    <li><a href="{{ url_for('main.by_tag',_method='GET',id=id, p = pagenation.page + 1) }}">Next</a> </li>
{% endif %}
</ul>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block postlist %}
    {% for p in posts %}
        <div class="panel panel-default">
            <div class="panel-body">
                <a style="color: #080808;text-decoration: none" href="{{ url_for('main.article',id=p.id) }}"><p class="lead"><strong>{{ p.title }}</strong></p></a>
                {{ p.body |truncate(200,True)|safe }}
            </div>
            <div class="panel-footer">
                {{ moment(p.modify_date).format('MMMM D, YYYY') }}  - 2 Comment
            </div>
        </div>
    {% endfor %}



{% endblock %}